# Generated by Django 4.2.24 on 2025-09-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(choices=[('argentina', 'Argentina'), ('belize', 'Belize'), ('bolivia', 'Bolivia'), ('brazil', 'Brazil'), ('canada', 'Canada'), ('chile', 'Chile'), ('costa_rica', 'Costa Rica'), ('ecuador', 'Ecuador'), ('guatemala', 'Guatemala'), ('mexico', 'Mexico'), ('honduras', 'Honduras'), ('nicaragua', 'Nicaragua'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('venezuela', 'Venezuela'), ('united_kingdom', 'United Kingdom'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
