# Generated by Django 4.2.24 on 2025-10-01 10:24

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_post_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('fav_country', models.CharField(choices=[('argentina', 'Argentina'), ('belize', 'Belize'), ('bolivia', 'Bolivia'), ('brazil', 'Brazil'), ('canada', 'Canada'), ('chile', 'Chile'), ('costa_rica', 'Costa Rica'), ('ecuador', 'Ecuador'), ('guatemala', 'Guatemala'), ('mexico', 'Mexico'), ('honduras', 'Honduras'), ('nicaragua', 'Nicaragua'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('venezuela', 'Venezuela'), ('united_kingdom', 'United Kingdom'), ('other', 'Other')], default='other', max_length=50)),
                ('wishlist_country', models.CharField(choices=[('argentina', 'Argentina'), ('belize', 'Belize'), ('bolivia', 'Bolivia'), ('brazil', 'Brazil'), ('canada', 'Canada'), ('chile', 'Chile'), ('costa_rica', 'Costa Rica'), ('ecuador', 'Ecuador'), ('guatemala', 'Guatemala'), ('mexico', 'Mexico'), ('honduras', 'Honduras'), ('nicaragua', 'Nicaragua'), ('paraguay', 'Paraguay'), ('peru', 'Peru'), ('venezuela', 'Venezuela'), ('united_kingdom', 'United Kingdom'), ('other', 'Other')], default='other', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traveller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
