# Generated by Django 4.2.24 on 2025-09-29 15:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
